routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("admin.transaction.index");
});

Route::group(["namespace"=>"Admin","as"=>"admin."],function(){
    Route::get("login","LoginCont@index")->name("login");
    Route::post("login","LoginCont@doLogin")->name("login.post");
    Route::get("logout","LoginCont@logout")->name("logout");

    Route::group(["prefix"=>"transaction","namespace"=>"Transaction","as"=>"transaction."],function(){
        Route::get("/","TransactionCont@index")->name("index");

        Route::group(["middleware"=>"auth"],function(){
            Route::get("recap","TransactionCont@recap")->name("recap");
            Route::get("add","TransactionCont@add")->name("add");
            Route::post("add","TransactionCont@store")->name("store");
            Route::get("{id}/edit","TransactionCont@edit")->name("edit");
            Route::post("{id}/edit","TransactionCont@store")->name("update");
            Route::get("{id}/delete","TransactionCont@destroy_transaction_data")->name("delete_transaction_data");
        });

    });

    Route::group(["prefix"=>"test","namespace"=>"Test","as"=>"test."],function(){
        Route::get("logic","LogicCont@index")->name("test-logic");
        Route::get("junior","LogicCont@junior")->name("test-junior");
    });
});

resources/views/admin/dashboard.blade.php
@extends("layouts.admin")

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield("title","Admin")</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ asset("css/site.css") }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="/">TONJOO</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="{{ route("admin.login.post") }}" method="post">
            {!! csrf_field() !!}
            <div class="form-group has-feedback">
                <input type="text" name="username" required class="form-control" placeholder="Username">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" required class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<script src="{{ asset("js/site.js") }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@include("admin.partial.errors")
@include("admin.partial.success")
</body>
</html>