routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("admin.transaction.index");
});

Route::group(["namespace"=>"Admin","as"=>"admin."],function(){
    Route::get("login","LoginCont@index")->name("login");
    Route::post("login","LoginCont@doLogin")->name("login.post");
    Route::get("logout","LoginCont@logout")->name("logout");

    Route::group(["prefix"=>"transaction","namespace"=>"Transaction","as"=>"transaction."],function(){
        Route::get("/","TransactionCont@index")->name("index");

        Route::group(["middleware"=>"auth"],function(){
            Route::get("recap","TransactionCont@recap")->name("recap");
            Route::get("add","TransactionCont@add")->name("add");
            Route::post("add","TransactionCont@store")->name("store");
            Route::get("{id}/edit","TransactionCont@edit")->name("edit");
            Route::post("{id}/edit","TransactionCont@store")->name("update");
            Route::get("{id}/delete","TransactionCont@destroy_transaction_data")->name("delete_transaction_data");
        });

    });

    Route::group(["prefix"=>"test","namespace"=>"Test","as"=>"test."],function(){
        Route::get("logic","LogicCont@index")->name("test-logic");
        Route::get("junior","LogicCont@junior")->name("test-junior");
    });
});

app/Http/Controllers/Admin/Transaction/TransactionCont.php
<?php

namespace App\Http\Controllers\Admin\Transaction;

use App\Http\Requests\StoreTransactionRequest;
use App\Models\Transaction;
use App\Models\TransactionItemData;
use Carbon\Carbon;
use DB;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TransactionCont extends Controller
{
    public function index(Request $request,TransactionItemData $itemData){
        $itemData = $itemData->newQuery();
        $opt = [
            "" => "All Category",
            "income" => "INCOME",
            "expense" => "EXPENSE"
        ];
        $per_page = 10;

        if($request->has("per_page") && $request->get("per_page") != ""){
            $per_page = $request->get("per_page");
        }



        $where = function($q) use ($request){
            if($request->has("term") && $request->get("term") != ""){
                foreach (explode(" ",$request->get("term")) as $term){
                    $q->whereHas("transaction_item",function($td) use ($term){
                        $td->whereHas("transaction",function($t) use ($term){
                            $t->where("description","like","%".$term."%");
                        });
                    });

                    $q->orWhere("name","like","%".$term."%");
                }
            }

            if($request->has("start_date") && $request->get("start_date") != ""){
                $q->whereHas("transaction_item",function($ti) use ($request){
                    $ti->whereHas("transaction",function($t) use ($request){
                        $t->whereDate("date_paid",">=",Carbon::createFromFormat("d/m/Y",$request->get("start_date"))->format("Y-m-d"));
                    });
                });
            }

            if($request->has("end_date") && $request->get("end_date") != ""){
                $q->whereHas("transaction_item",function($ti) use ($request){
                    $ti->whereHas("transaction",function($t) use ($request){
                        $t->whereDate("date_paid","<=",Carbon::createFromFormat("d/m/Y",$request->get("end_date"))->format("Y-m-d"));
                    });
                });
            }

            if($request->has("category") && $request->get("category") != ""){
                $q->whereHas("transaction_item",function($ti) use ($request){
                    $ti->where("category",$request->get("category"));
                });
            }
        };

        $itemData->where($where);
        $itemData->with("transaction_item.transaction");
        $itemData = $itemData->paginate($per_page)->appends($request->query());

        return view("admin.transaction.index",compact("itemData","opt"));
    }
    public function add(){
        $opt = [
            "income" => "INCOME",
            "expense" => "EXPENSE"
        ];
        $transaction = null;
        return view("admin.transaction.add",compact("opt","transaction"));
    }

    public function edit($id,Transaction $transaction){
        $opt = [
            "income" => "INCOME",
            "expense" => "EXPENSE"
        ];
        $transaction = $transaction->newQuery()->findOrFail($id);
        return view("admin.transaction.edit",compact("opt","transaction"));
    }

    public function recap(Request $request, Transaction $transaction){
        $transaction = $transaction->newQuery();
        $opt = [
            "" => "All Category",
            "income" => "INCOME",
            "expense" => "EXPENSE"
        ];

        $where = function($q) use ($request){
            if($request->has("term") && $request->get("term") != ""){
                $q->where("description","like","%".$request->get("term")."%");
            }

            if($request->has("start_date") && $request->get("start_date") != ""){
                $q->whereDate("date_paid",">=",Carbon::createFromFormat("d/m/Y",$request->get("start_date"))->format("Y-m-d"));
            }

            if($request->has("end_date") && $request->get("end_date") != ""){
                $q->whereDate("date_paid","<=",Carbon::createFromFormat("d/m/Y",$request->get("end_date"))->format("Y-m-d"));
            }

            if($request->has("category") && $request->get("category") != ""){
                $q->where("category",$request->get("category"));
            }
        };


        $itemData = $transaction
                ->join("transaction_items as ti","ti.transaction_id","=","transactions.id")
                ->join("transaction_item_datas as tid","tid.transaction_item_id","=","ti.id")
                ->groupBy(["ti.category","tid.transaction_item_id"])
                ->selectRaw("transactions.*,SUM(tid.amount) as total,ti.category")
                ->orderBy("transactions.created_at","asc")
                ->where($where)
                ->paginate(10);

//        return $transaction;

        return view("admin.transaction.recap",compact("itemData","opt"));
    }

    public function store(StoreTransactionRequest $request,Transaction $transaction){
        if($request->has("date_paid")){
            $request->merge(["date_paid"=>Carbon::createFromFormat("d/m/Y",$request->input("date_paid"))->format("Y-m-d")]);
        }
        $data = $request->except(["id","_token","category","trans_data"]);
        DB::beginTransaction();

        try{

            $store = $transaction->newQuery()->updateOrCreate(["id"=>$request->input("id")],$data);
//            return $store;
            if($request->has("id")){
                $clear = $transaction->newQuery()->find($store->id);
                $clear->transaction_items()->delete();
            }


            foreach ($request->input("category") as $k=>$category) {
                $store_category = $store->transaction_items()->create([
                    "category" => $category
                ]);

                $transaction_item_data = $request->input("trans_data");
                $transaction_item_data = json_decode($transaction_item_data[$k],true);
                foreach ($transaction_item_data as $v){
                    $store_category->transaction_item_data()->create($v);
                }
            }


            DB::commit();
        }catch (Exception $e){
            DB::rollBack();
            return back()->withErrors(["failed"=>"Periksa kembali data transaksi."])->withInput();
        }

        return redirect()->route("admin.transaction.index")->withSuccess("Data tersimpan.");
    }

    public function destroy_transaction_data($id,TransactionItemData $itemData){
        $itemData->newQuery()->findOrFail($id)->delete();
        return back()->withSuccess("Data telah dihapus");
    }
}

resources/views/admin/transaction/add.blade.php
@extends("layouts.admin")
@section("page_header","Input Data Transaksi")
@section("breadcrumb")
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Data Transaksi</a></li>
        <li class="active">Input Data Transaksi</li>
    </ol>
@stop
@push("contents")
    {!! Form::open(["class"=>"form-horizontal","onsubmit"=>"submitTransaction(event)"]) !!}
    @include("admin.transaction.form")
    {!! Form::close() !!}
    @include("admin.transaction.template")

@endpush

resources/views/admin/transaction/edit.blade.php
@extends("layouts.admin")
@section("page_header","Edit Data Transaksi")
@section("breadcrumb")
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Data Transaksi</a></li>
        <li><a href="{{ route("admin.transaction.index") }}"><i class="fa fa-dashboard"></i> List Data Transaksi</a></li>
        <li class="active">Edit Data Transaksi</li>
    </ol>
@stop
@push("contents")
    {!! Form::model($transaction,["class"=>"form-horizontal","onsubmit"=>"submitTransaction(event)"]) !!}
    {!! Form::hidden("id",$transaction->id) !!}
    @include("admin.transaction.form")
    {!! Form::close() !!}
    @include("admin.transaction.template")

@endpush

resources/views/admin/transaction/form.blade.php
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-body">
                <div class="col-sm-6">
                    <div class="form-group">
                        {!! Form::label("description","Description",["class"=>"control-label col-sm-2"]) !!}
                        <div class="col-sm-10">
                            {!! Form::textarea("description",null,["class"=>"form-control","required","rows"=>2]) !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        {!! Form::label("code","Code",["class"=>"control-label col-sm-3"]) !!}
                        <div class="col-sm-9">
                            {!! Form::text("code",null,["class"=>"form-control","required"]) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label("rate_euro","Rate Euro",["class"=>"control-label col-sm-3"]) !!}
                        <div class="col-sm-9">
                            {!! Form::text("rate_euro",null,["class"=>"form-control","required"]) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label("date_paid","Date Paid",["class"=>"control-label col-sm-3"]) !!}
                        <div class="col-sm-9">
                            <div class="input-group" id="date-paid">
                                {!! Form::text("date_paid",$transaction != null ? $transaction->date_paid->format("d/m/Y"):null,["class"=>"form-control","required"]) !!}
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Data Transaksi</h3>
            </div>
            <div class="panel-body">
                <div class="transaction-item-container">
                    @if($transaction != null)
                        @foreach($transaction->transaction_items as $item)
                            <div class="panel panel-danger">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-sm-12 text-right">
                                            <button type="button" class="btn btn-xs btn-danger text-bold" onclick="removeTransItemRow(event)">x</button>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <label for="" class="control-label col-sm-3">Category</label>
                                            <div class="col-sm-3">
                                                {!! Form::select("category[]",$opt,$item->category,["class"=>"form-control","required"]) !!}
                                                {!! Form::hidden("trans_data[]",$item->data_string(),["class"=>"trans_data"]) !!}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="" class="control-label col-sm-3">&nbsp;</label>
                                            <div class="col-sm-7">
                                                <div class="rTable">
                                                    <div class="rTableRow">
                                                        <div class="rTableHead"><strong>Nama Transaksi</strong></div>
                                                        <div class="rTableHead text-right"><strong>Nominal</strong></div>
                                                    </div>
                                                    <div class="row-container">
                                                        @foreach($item->transaction_item_data as $itemData)
                                                            <div class="rTableRow">
                                                                <div class="rTableCell">{{ $itemData->name }}</div>
                                                                <div class="rTableCell text-right"><span>{{ $itemData->amount }} </span> &nbsp;&nbsp;<i onclick="removeTransDataRow(event)" class="fa fa-trash cursor-pointer"></i></div>
                                                            </div>
                                                        @endforeach
                                                    </div>

                                                    <div class="rTableRow">
                                                        <div class="rTableCell"><input type="text" class="form-control transaction-name" {{ $transaction == null ? "required":"" }}></div>
                                                        <div class="rTableCell">
                                                            <div class="input-group">
                                                                <input type="number" class="form-control transaction-amount" {{ $transaction == null ? "required":"" }}>
                                                                <div class="input-group-btn">
                                                                    <button type="button" onclick="addTransData(event)" class="btn btn-info text-bold">+</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="panel panel-danger">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 text-right">
                                        <button type="button" class="btn btn-xs btn-danger text-bold" onclick="removeTransItemRow(event)">x</button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group">
                                        <label for="" class="control-label col-sm-3">Category</label>
                                        <div class="col-sm-3">
                                            {!! Form::select("category[]",$opt,null,["class"=>"form-control","required"]) !!}
                                            {!! Form::hidden("trans_data[]",null,["class"=>"trans_data"]) !!}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="" class="control-label col-sm-3">&nbsp;</label>
                                        <div class="col-sm-7">
                                            <div class="rTable">
                                                <div class="rTableRow">
                                                    <div class="rTableHead"><strong>Nama Transaksi</strong></div>
                                                    <div class="rTableHead text-right"><strong>Nominal</strong></div>
                                                </div>
                                                <div class="row-container">

                                                </div>

                                                <div class="rTableRow">
                                                    <div class="rTableCell"><input type="text" class="form-control transaction-name" required></div>
                                                    <div class="rTableCell">
                                                        <div class="input-group">
                                                            <input type="number" class="form-control transaction-amount" required>
                                                            <div class="input-group-btn">
                                                                <button type="button" onclick="addTransData(event)" class="btn btn-info text-bold">+</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif

                </div>

                <div class="row">
                    <div class="col-sm-12 text-right">
                        <button type="button" onclick="addTransItem(event)" class="btn btn-primary">Tambah</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 text-right">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href="{{ route("admin.transaction.index") }}" onclick="return confirm('Batal ?')" class="btn btn-danger">Batal</a>
    </div>
</div>

@push("scripts")
    <script>
        $(function(){
            $("#date-paid").datetimepicker({
                format:"DD/MM/YYYY",
                locale:'id'
            });
        });
    </script>
@endpush

resources/views/admin/transaction/index.blade.php
@extends("layouts.admin")
@section("page_header","List Data Transaksi")
@section("breadcrumb")
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Data Transaksi</a></li>
        <li class="active">List Data Transaksi</li>
    </ol>
@stop

@push("contents")
    <div class="row" id="filter">
        <div class="col-sm-2">
            @auth
                <a href="{{ route("admin.transaction.add") }}" class="btn btn-primary">Tambah Transaksi</a>
            @endauth
        </div>
        <div class="col-sm-10">
            <form class="row" id="form-filter">
                <input type="hidden" name="per_page" id="per_page" value="{{ Request::get("per_page") }}">
                <div class="col-sm-3">
                    <div class="input-group" id="sd">
                        <input type="text" class="form-control" id="start-date" name="start_date" value="{{ Request::get("start_date") }}" placeholder="Start Date">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="input-group" id="ed">
                        <input type="text" class="form-control" id="end-date" name="end_date" value="{{ Request::get("end_date") }}" placeholder="End Date">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>

                <div class="col-sm-2">
                    {!! Form::select("category",$opt,Request::get("category"),['class'=>'form-control']) !!}
                </div>

                <div class="col-sm-3">
                    <input type="text" class="form-control" id="term" name="term" value="{{ Request::get("term") }}" placeholder="Keywords">
                </div>

                <div class="col-sm-1">
                    <button class="btn btn-primary btn-block"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel">
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr class="bg-gray">
                            <th>No</th>
                            <th>Deskripsi</th>
                            <th class="text-right">Code</th>
                            <th class="text-right">Rate Euro</th>
                            <th>Date Paid</th>
                            <th>Kategori</th>
                            <th>Nama Transaksi</th>
                            <th class="text-right">Nominal(IDR)</th>
                            @auth
                            <th>Aksi</th>
                            @endauth
                        </tr>
                        </thead>
                        @forelse($itemData as $item)
                            <tr>
                                <td>{{ ($itemData->currentPage()-1) * $itemData->perPage() + $loop->index + 1 }}</td>
                                <td>{{ $item->transaction_item->transaction->description }}</td>
                                <td class="text-right">{{ $item->transaction_item->transaction->code }}</td>
                                <td class="text-right">{{ nf($item->transaction_item->transaction->rate_euro) }}</td>
                                <td>{{ $item->transaction_item->transaction->date_paid->format("d/m/Y") }}</td>
                                <td>{{ $item->transaction_item->category }}</td>
                                <td>{{ $item->name }}</td>
                                <td class="text-right">{{ nf($item->amount) }}</td>
                                @auth
                                <td>
                                    <a href="{{ route("admin.transaction.edit",["id"=>$item->transaction_item->transaction->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
                                    <a href="{{ route("admin.transaction.delete_transaction_data",["id"=>$item->id]) }}" onclick="return confirm('Delete data?')" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>
                                </td>
                                @endauth
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-center" colspan="{{ auth()->check() ? "8":"7" }}">Tidak ada data.</td>
                                </tr>
                        @endforelse
                    </table>
                </div>
            </div>
        </div>
    </div>
@endpush

@push("footer")
    <div class="row">
        <div class="col-sm-6">
            {!! Form::select("per_page",[10=>10,20=>20,50=>50],Request::get("per_page"),["onchange"=>"populatePerPage(event)"]) !!}
            &nbsp;
            Menampilkan {{ $itemData->count() }} dari {{ $itemData->total() }} data
        </div>
        <div class="col-sm-6 text-right">
            {!! $itemData->render() !!}
        </div>
    </div>
@endpush

@push("scripts")
    <script type="text/javascript">
        $(function () {
            var sd = $('#sd').datetimepicker({
                format:"DD/MM/YYYY"
            });
            var ed = $('#ed').datetimepicker({
                format:"DD/MM/YYYY",
                useCurrent: false //Important! See issue #1075
            });
            sd.on("dp.change", function (e) {
                ed.data("DateTimePicker").minDate(e.date);
            });
            ed.on("dp.change", function (e) {
                sd.data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>
@endpush

resources/views/admin/transaction/recap.blade.php
@extends("layouts.admin")
@section("page_header","Rekap Transaksi")
@section("breadcrumb")
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Data Transaksi</a></li>
        <li class="active">Rekap Transaksi</li>
    </ol>
@stop

@push("contents")
    <div class="row" id="filter">
        <div class="col-sm-2">
            {{--<a href="{{ route("admin.transaction.add") }}" class="btn btn-primary">Tambah Transaksi</a>--}}
        </div>
        <div class="col-sm-10">
            <form class="row" id="form-filter">
                <input type="hidden" name="per_page" id="per_page" value="{{ Request::get("per_page") }}">
                <div class="col-sm-3">
                    <div class="input-group" id="sd">
                        <input type="text" class="form-control" id="start-date" name="start_date" value="{{ Request::get("start_date") }}" placeholder="Start Date">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="input-group" id="ed">
                        <input type="text" class="form-control" id="end-date" name="end_date" value="{{ Request::get("end_date") }}" placeholder="End Date">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>

                <div class="col-sm-2">
                    {!! Form::select("category",$opt,Request::get("category"),['class'=>'form-control']) !!}
                </div>

                <div class="col-sm-3">
                    <input type="text" class="form-control" id="term" name="term" value="{{ Request::get("term") }}" placeholder="Keywords">
                </div>

                <div class="col-sm-1">
                    <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel">
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr class="bg-gray">
                            <th>No</th>
                            <th>Deskripsi</th>
                            <th>Tanggal</th>
                            <th>Kategori</th>
                            <th class="text-right">Nominal(IDR)</th>
                        </tr>
                        </thead>
                        @forelse($itemData as $item)
                            <tr>
                                <td>{{ ($itemData->currentPage()-1) * $itemData->perPage() + $loop->index + 1 }}</td>
                                <td>{{ $item->description }}</td>
                                <td>{{ $item->date_paid->format("d/m/Y") }}</td>
                                <td>{{ $item->category }}</td>
                                <td class="text-right">{{ nf($item->total)}}</td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-center" colspan="5">Tidak ada data.</td>
                                </tr>
                        @endforelse
                    </table>
                </div>
            </div>
        </div>
    </div>
@endpush

@push("footer")
    <div class="row">
        <div class="col-sm-6">
            {!! Form::select("per_page",[10=>10,20=>20,50=>50],Request::get("per_page"),["onchange"=>"populatePerPage(event)"]) !!}
            &nbsp;
            Menampilkan {{ $itemData->count() }} dari {{ $itemData->total() }} data
        </div>
        <div class="col-sm-6 text-right">
            {!! $itemData->render() !!}
        </div>
    </div>
@endpush

@push("scripts")
    <script type="text/javascript">
        $(function () {
            var sd = $('#sd').datetimepicker({
                format:"DD/MM/YYYY"
            });
            var ed = $('#ed').datetimepicker({
                format:"DD/MM/YYYY",
                useCurrent: false //Important! See issue #1075
            });
            sd.on("dp.change", function (e) {
                ed.data("DateTimePicker").minDate(e.date);
            });
            ed.on("dp.change", function (e) {
                sd.data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>
@endpush